# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: rusty.straussbrowndogs@gmail.com
author_name: RobertRusty
has_binder: true
has_settings: true
kind: frontend
labextension_name: mosaicLab
project_short_description: 'Free your code from the archaic linear ''scroll'' of old,
    and embrace the freedom of flexible, gridded, dashboarding layouts. '
python_name: mosaicLab
repository: https://github.com/robertstrauss/jupytermosaic
test: true

