# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: robertstrauss@pm.me
author_name: Robert Strauss
has_binder: true
has_settings: true
kind: frontend
labextension_name: mosaic-lab
project_short_description: Arrange Jupyter notebook cells in any way two-dimensionally.
    Present your code compactly in Zoom video confrences. Let your Jupyter notebook
    tell the story and be self-documenting in itself, like a poster presentation.
    Eliminate white space in your notebook and take advantage of unused screen real
    estate.
python_name: mosaic_lab
repository: https://github.com/robertstrauss/jupytermosaic
test: true

